version: 0.2

env:
  variables:
    S3_BUCKET: "tier-1-bucket"

phases:
  install:
    runtime-versions:
      nodejs: latest
  build:
    commands:
      - echo Build started on `date`
      - echo Installing source NPM dependencies...
      - cd express-minapp
      - npm install
      - echo Compiling the Node.js code
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - express-minapp/src/index.js
    - express-minapp/src/middlewares.js
    - express-minapp/package.json
    - express-minapp/node_modules/**/*
    - express-minapp/Procfile
  discard-paths: yes

cache:
  paths:
    - node_modules/**/*