AWSTemplateFormatVersion: 2010-09-09
Description: Apper DevOps Engineer Technical Challenge - Sammy Medina - Tier 1 - CI/CD

Parameters:
  # Shared Parameters
  ChallengeTier:
    Description: Please enter the challenge tier for this stack (e.g. 1)
    Type: String
    Default: 1
  Environment:
    Description: Please enter the environment for this stack (e.g. STG, PROD)
    Type: String
    Default: DEV
  AWSMainAccountNumber:
    Description: Please enter the AWS account number for this stack
    Type: String
    Default: 485323199507

# Mappings:

# Conditions:

Resources:
  ### S3 ###
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Sub tier-${ChallengeTier}-cicd
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: TIER
          Value: !Ref ChallengeTier
        - Key: ENV
          Value: !Ref Environment
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket #required
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal: "*"
            Action: "s3:*"
            Resource: !Join [ "", [ "arn:aws:s3:::", !Ref S3Bucket, /* ] ]
            Condition:
              StringLike:
                "aws:userId":
                  - !Join [ ":", [ !GetAtt CodePipelineIAMRole.RoleId, "*" ] ]
                  - !Join [ ":", [ !GetAtt CodeBuildIAMRole.RoleId, "*" ] ]
                  - !Ref AWSMainAccountNumber

  ### IAM ###
  CodePipelineIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
                - s3.amazonaws.com
                - cloudformation.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: !Sub tier-${ChallengeTier}-codepipeline-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - "iam:PassRole"
                Resource: "*"
                Effect: "Allow"
                Condition:
                  StringEqualsIfExists:
                    iam:PassedToService:
                      - "cloudformation.amazonaws.com"
                      - "ec2.amazonaws.com"
                      - "codepipeline.amazonaws.com"
                      - "codebuild.amazonaws.com"
                      - "codestar-connections.amazonaws.com"
                      - "s3.amazonaws.com"
              - Action:
                  - "codedeploy:CreateDeployment"
                  - "codedeploy:GetApplicationRevision"
                  - "codedeploy:GetDeployment"
                  - "codedeploy:GetDeploymentConfig"
                  - "codedeploy:RegisterApplicationRevision"
                Resource: "*"
                Effect: "Allow"
              - Action:
                  - "cloudformation:CreateStack"
                  - "cloudformation:DeleteStack"
                  - "cloudformation:DescribeStacks"
                  - "cloudformation:UpdateStack"
                  - "cloudformation:CreateChangeSet"
                  - "cloudformation:DeleteChangeSet"
                  - "cloudformation:DescribeChangeSet"
                  - "cloudformation:ExecuteChangeSet"
                  - "cloudformation:SetStackPolicy"
                  - "cloudformation:ValidateTemplate"
                  - "iam:PassRole"
                Resource: "*"
                Effect: "Allow"
              - Action:
                  - "codebuild:BatchGetBuilds"
                  - "codebuild:StartBuild"
                  - "codebuild:BatchGetBuildBatches"
                  - "codebuild:StartBuildBatch"
                Resource: !GetAtt CodeBuildProjectBuildExpressMiniapp.Arn
                Effect: "Allow"
              - Action:
                  - "codestar-connections:UseConnection"
                Resource: !Ref CodePipelineGithubConnection
                Effect: "Allow"
              - Action:
                  - "s3:*"
                Resource: !GetAtt S3Bucket.Arn
                Effect: "Allow"
      Description: The service role used for CodePipeline
      RoleName: !Sub tier-${ChallengeTier}-codepipeline-service-role
      Tags:
        - Key: TIER
          Value: !Ref ChallengeTier
        - Key: ENV
          Value: !Ref Environment
  
  CodeBuildIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
                - s3.amazonaws.com
                - cloudformation.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: !Sub tier-${ChallengeTier}-codebuild-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - "s3:ListBucket"
                  - "s3:GetBucketAcl"
                  - "logs:CreateLogGroup"
                  - "logs:PutLogEvents"
                  - "s3:PutObject"
                  - "s3:GetObject"
                  - "codebuild:CreateReportGroup"
                  - "codebuild:CreateReport"
                  - "logs:CreateLogStream"
                  - "codebuild:UpdateReport"
                  - "s3:PutObjectVersionAcl"
                  - "s3:GetBucketLocation"
                  - "codebuild:BatchPutTestCases"
                  - "s3:PutObjectAcl"
                  - "s3:GetObjectVersion"
                Resource:
                  - "arn:aws:s3:::*"
                  - "arn:aws:logs:*:*:log-group:/aws/codebuild/*"
                  - "arn:aws:codebuild:*"
                Effect: "Allow"
              - Action:
                  - "codestar-connections:UseConnection"
                Resource: !Ref CodePipelineGithubConnection
                Effect: "Allow"

  ### CodeStar Connection ###
  CodePipelineGithubConnection:
    Type: AWS::CodeStarConnections::Connection
    Properties:
      ConnectionName: !Sub tier-${ChallengeTier}-github-connection #required
      ProviderType: GitHub
      Tags:
        - Key: TIER
          Value: !Ref ChallengeTier
        - Key: ENV
          Value: !Ref Environment

  ### Code Build ###
  CodeBuildProjectBuildExpressMiniapp:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts: #required
        Type: CODEPIPELINE
      Cache:
        Type: S3
        Location: !Join [ "/", [ !Ref S3Bucket, "cache" ] ]
      ConcurrentBuildLimit: 3
      Description: The CodeBuild project for building the express-miniapp project
      Environment: #required
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:2.0
        Type: LINUX_CONTAINER
      Name: !Sub tier-${ChallengeTier}-codebuild-build-express-miniapp
      QueuedTimeoutInMinutes: 5
      ServiceRole: !GetAtt CodeBuildIAMRole.Arn #required
      Source: #required
        Type: CODEPIPELINE
      Tags:
        - Key: TIER
          Value: !Ref ChallengeTier
        - Key: ENV
          Value: !Ref Environment
      TimeoutInMinutes: 5

  ### Code Pipeline ###
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Location: !Ref S3Bucket
        Type: S3
      Name: !Sub tier-${ChallengeTier}-pipeline
      RestartExecutionOnUpdate: true
      RoleArn: !GetAtt CodePipelineIAMRole.Arn
      Stages: #required
        - Name: Pre-Build
          Actions:
            - ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: 1
              Configuration:
                ConnectionArn: !GetAtt CodePipelineGithubConnection.ConnectionArn
                FullRepositoryId: SammyJumpstart23/apper-devops-tech-challenge
                BranchName: !Sub tier-${ChallengeTier}
                OutputArtifactFormat: CODEBUILD_CLONE_REF
              Name: GithubSource
              OutputArtifacts:
                - Name: express-miniapp
              RunOrder: 1
        - Name: Build
          Actions:
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Ref CodeBuildProjectBuildExpressMiniapp
                PrimarySource: express-miniapp
              Name: Build-Node
              InputArtifacts:
                - Name: express-miniapp
              OutputArtifacts:
                - Name: built-express-miniapp
              RunOrder: 1
        - Name: Deploy
          Actions:
            - ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: ElasticBeanstalk
                Version: 1
              Configuration:
                
              Name: Build-Node
              InputArtifacts:
                - Name: express-miniapp
              OutputArtifacts:
                - Name: built-express-miniapp
              RunOrder: 1
      Tags:
        - Key: Name
          Value: !Sub tier-${ChallengeTier}-codepipeline
        - Key: TIER
          Value: !Ref ChallengeTier
        - Key: ENV
          Value: !Ref Environment

  # Elastic Beanstalk
  ExpressApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: !Sub tier-${ChallengeTier}-application
      Description: AWS Elastic Beanstalk Application for Apper DevOps Engineer Technical Challenge - Tier 1

  ExpressApplicationVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName: !Ref ExpressApplication
      SourceBundle:
        S3Bucket: !Ref S3Bucket
        S3Key: express-miniapp.zip

  ExpressConfigurationTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName: !Ref ExpressApplication
      Description: AWS Elastic Beanstalk Application Configuration
      EnvironmentId: String
      OptionSettings:
        - ConfigurationOptionSetting
      PlatformArn: String
      SolutionStackName: String
      SourceConfiguration:
        SourceConfiguration

Outputs:
  S3Bucket:
    Description: A reference to the S3 Bucket for the Elastic Beanstalk application
    Value: !Ref S3Bucket
  CodePipeline:
    Description: A reference to the CodePipeline
    Value: !Ref CodePipeline
