AWSTemplateFormatVersion: 2010-09-09
Description: Apper DevOps Engineer Technical Challenge - Sammy Medina - Tier 1 - EB
# Metadata: 

Parameters: 
  # Shared Parameters
  ChallengeTier:
    Description: Please enter the challenge tier for this stack (e.g. 1)
    Type: String
    Default: 1
  Environment:
    Description: Please enter the environment for this stack (e.g. STG, PROD)
    Type: String
    Default: DEV

# Mappings: 

# Conditions: 

Resources: 
  # Elastic Beanstalk
  ExpressApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: !Sub tier-${ChallengeTier}-application
      Description: AWS Elastic Beanstalk Application for Apper DevOps Engineer Technical Challenge - Tier 1

  ExpressApplicationVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName: !Ref ExpressApplication
      SourceBundle:
        S3Bucket: !Ref S3Bucket
        S3Key: express-miniapp.zip

  ExpressConfigurationTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName: !Ref ExpressApplication
      Description: String
      EnvironmentId: String
      OptionSettings:
        - ConfigurationOptionSetting
      PlatformArn: String
      SolutionStackName: String
      SourceConfiguration:
        SourceConfiguration

Outputs: