apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: express-minapp-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: express-minapp-service
                port:
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: express-minapp-service
spec:
  selector:
    app: express-minapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1337
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-minapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: express-minapp
  template:
    metadata:
      labels:
        app: express-minapp
    spec:
      containers:
        - name: express-minapp
          image: 485323199507.dkr.ecr.ap-southeast-1.amazonaws.com/rsmedina-tier-3-ecr:latest
          ports:
            - containerPort: 1337
          env:
            - name: HOST
              value: $HOST
            - name: USERNAME
              value: $USERNAME
            - name: PASSWORD
              value: $PASSWORD
            - name: DATABASE
              value: $DATABASE
          resources:
            requests:
              cpu: "10m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "500Mi"
